### ISSUE TITLE
NetCDF4 interface compile error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#1]
```
What steps will reproduce the problem?

1. Installing netcdf-4.0-2008013102 on 32- and -64-bit Linux platforms with
the recommended gfortran 4.1.2 flags and libraries, e.g. the following HDF
library.

configure --prefix=/opt/gfortran/netcdf-4.0-2008013102 --enable-netcdf-4
--with-hdf5=/opt/gfortran/hdf5-1.8.0-rc2 --with-zlib=/usr

2. Installing hdf5-1.8.0-rc2 on 32- and 64-bit Linux platforms with the
recommended gfortran 4.1.2 flags.

configure --prefix=/opt/gfortran/hdf5-1.8.0-rc2 --enable-fortran
--enable-cxx --with-zlib=/usr

3. Attempting to build netCDF4-0.7.3.1

What is the expected output? What do you see instead?

The error message, consistent across 4 platforms thus far:

compile options: '-I/opt/gfortran/netcdf-4.0-2008013102/include
-I/opt/gfortran/hdf5-1.8.0-rc2/include
-I/usr/lib/python2.5/site-packages/numpy/core/include
-I/usr/include/python2.5 -c'
gcc: netCDF4.c
netCDF4.c: In function ‘__pyx_pf_7netCDF4_8Variable___init__’:
netCDF4.c:7882: error: ‘NC_CHUNK_SUB’ undeclared (first use in this 
function)
netCDF4.c:7882: error: (Each undeclared identifier is reported only once
netCDF4.c:7882: error: for each function it appears in.)
netCDF4.c:7905: error: ‘NC_CHUNK_SEQ’ undeclared (first use in this 
function)
netCDF4.c:8088: warning: passing argument 3 of ‘nc_def_var_chunking’ makes
integer from pointer without a cast
netCDF4.c:8088: error: too many arguments to function ‘nc_def_var_chunking’
netCDF4.c: In function ‘__pyx_pf_7netCDF4_8Variable_chunking’:
netCDF4.c:9836: error: too many arguments to function ‘nc_inq_var_chunking’
netCDF4.c:9963: error: ‘NC_CHUNK_SEQ’ undeclared (first use in this 
function)
netCDF4.c:9986: error: ‘NC_CHUNK_SUB’ undeclared (first use in this 
function)
netCDF4.c:10009: error: ‘NC_CHUNK_SIZES’ undeclared (first use in this
function)
netCDF4.c: In function ‘__pyx_pf_7netCDF4_getlibversion’:
netCDF4.c:14529: warning: assignment discards qualifiers from pointer
target type
netCDF4.c: In function ‘initnetCDF4’:
netCDF4.c:20679: warning: integer constant is too large for ‘long’ type
netCDF4.c:20690:62: warning: integer constant is so large that it is unsigned
netCDF4.c:20690: warning: this decimal constant is unsigned only in ISO C90
netCDF4.c:20690: warning: integer constant is too large for ‘long’ type
netCDF4.c: In function ‘__pyx_pf_7netCDF4_8Variable___init__’:
netCDF4.c:7882: error: ‘NC_CHUNK_SUB’ undeclared (first use in this 
function)
netCDF4.c:7882: error: (Each undeclared identifier is reported only once
netCDF4.c:7882: error: for each function it appears in.)
netCDF4.c:7905: error: ‘NC_CHUNK_SEQ’ undeclared (first use in this 
function)
netCDF4.c:8088: warning: passing argument 3 of ‘nc_def_var_chunking’ makes
integer from pointer without a cast
netCDF4.c:8088: error: too many arguments to function ‘nc_def_var_chunking’
netCDF4.c: In function ‘__pyx_pf_7netCDF4_8Variable_chunking’:
netCDF4.c:9836: error: too many arguments to function ‘nc_inq_var_chunking’
netCDF4.c:9963: error: ‘NC_CHUNK_SEQ’ undeclared (first use in this 
function)
netCDF4.c:9986: error: ‘NC_CHUNK_SUB’ undeclared (first use in this 
function)
netCDF4.c:10009: error: ‘NC_CHUNK_SIZES’ undeclared (first use in this
function)
netCDF4.c: In function ‘__pyx_pf_7netCDF4_getlibversion’:
netCDF4.c:14529: warning: assignment discards qualifiers from pointer
target type
netCDF4.c: In function ‘initnetCDF4’:
netCDF4.c:20679: warning: integer constant is too large for ‘long’ type
netCDF4.c:20690:62: warning: integer constant is so large that it is unsigned
netCDF4.c:20690: warning: this decimal constant is unsigned only in ISO C90
netCDF4.c:20690: warning: integer constant is too large for ‘long’ type
error: Command "gcc -pthread -fno-strict-aliasing -DNDEBUG -O2 -g -pipe
-Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector
--param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic
-fasynchronous-unwind-tables -D_GNU_SOURCE -fPIC -fPIC
-I/opt/gfortran/netcdf-4.0-2008013102/include
-I/opt/gfortran/hdf5-1.8.0-rc2/include
-I/usr/lib/python2.5/site-packages/numpy/core/include
-I/usr/include/python2.5 -c netCDF4.c -o
build/temp.linux-i686-2.5/netCDF4.o" failed with exit status 1

What version of the product are you using? On what operating system?


Please provide any additional information below.

This version of NetCDF4 will not compile successfully with the
--enable-netcdf-4 flag against versions of HDF5 older than this one.  Russ
Rew tells me that's due to the final change in the HDF5 API before the
release of HDF5 1.8.0.

On the other hand, the NetCDF3 version works fine with NetCDF 3.6.2.
```

Original issue reported on code.google.com by `steven.k...@gmail.com` on 2 Feb 2008 at 5:44

**Comment by GoogleCodeExporter** [comment]
```
I think you forgot to include --enable-hl when compiling HDF5
```

Original comment by `whitaker.jeffrey@gmail.com` on 29 Feb 2008 at 11:20

**Comment by GoogleCodeExporter** [comment]
```
Hi.

  I have a very similar error message also on a 64-bit linux machine.  I compiled hdf5 with the --enable-hl 
option (I believe I've done this correctly) but that seems to not have changed 
the error.  Thanks if you have any 
other suggestions.
```

Original comment by `Edwards....@gmail.com` on 24 Apr 2008 at 12:57

**Comment by GoogleCodeExporter** [comment]
```
I think you must be using a recent netCDF4 snapshot.  The released version of 
the module won't work with the 
new snapshots, you'll need to use the SVN version of netcdf4-python instead.
```

Original comment by `whitaker.jeffrey@gmail.com` on 24 Apr 2008 at 1:32

**Comment by GoogleCodeExporter** [comment]
```
Hi.  Yes, I was running today's netCDF4 snapshot.  Thanks for the suggestion.  
With the svn version of netcdf4-
python, everything seems to install properly, or at least without error 
messages, but when I try and run tests, on 
import netCDF4 I get an error:
ImportError: /home/cae/local/python/lib64/python2.4/site-packages/netCDF4.so: 
undefined symbol: 
inflateEnd

Again, any suggestions are appreciated.


```

Original comment by `Edwards....@gmail.com` on 24 Apr 2008 at 3:41

**Comment by GoogleCodeExporter** [comment]
```
inflateEnd looks like a symbol from the zlib library.  I'm pretty sure setup.py 
links
libz, so I don't know why this would be happening. If you are on linux, could 
you
send the result of 

ldd /home/cae/local/python/lib64/python2.4/site-packages/netCDF4.so

or macos x

otool -L /home/cae/local/python/lib64/python2.4/site-packages/netCDF4.so
```

Original comment by `whitaker.jeffrey@gmail.com` on 24 Apr 2008 at 4:58

**Comment by GoogleCodeExporter** [comment]
```
[cae@bluewater ~]$ ldd 
/home/cae/local/python/lib64/python2.4/site-packages/netCDF4.so
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaab030000)
    libc.so.6 => /lib64/libc.so.6 (0x00002aaaab24a000)
    /lib64/ld-linux-x86-64.so.2 (0x0000555555554000)


```

Original comment by `Edwards....@gmail.com` on 24 Apr 2008 at 5:22

**Comment by GoogleCodeExporter** [comment]
```
I don't see the hdf5, netcdf or zlib libs in there.  Did you set the HDF5_DIR 
and
NETCDF4_DIR env vars?  Please capture the output of build and mail it to me 
directly
(jeffrey.s.whitaker@noaa.gov).
```

Original comment by `whitaker.jeffrey@gmail.com` on 24 Apr 2008 at 5:28

**Comment by GoogleCodeExporter** [comment]
```
Yes, the environment variables were set properly, but the hdf and netcdf 
libraries were not built as shared.  Now 
that they are, it works.  Thanks for your help.
```

Original comment by `Edwards....@gmail.com` on 25 Apr 2008 at 4:33

**Comment by GoogleCodeExporter** [comment]
```
The addition of --enable-hl worked when using the latest versions as of June 4, 
i.e.

hdf5-1.8.0-snap5
netcdf-4.0-snapshot2008060210

as well as using yesterday's version of netcdf4-python from checkout.

Thanks.
```

Original comment by `steven.k...@gmail.com` on 4 Jun 2008 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
I guess I should also mention that if you're compiling on a 64-bit machine with
gfortran, you either have to use the --enable-shared option when compiling 
NetCDF or
add the -fPIC compiler flag if you're not using --enable-shared.

I have directories continaing both shared and not shared versions of NetCDF 
since
ROMS doesn't seem to like the shared version, at least not when using gfortran.

I'm not going to get into how many different versions I compile when using 
ifort or
other commercial compilers, as I prefer to get all misty-eyed and nostalgic 
about the
days of one compiler on one platform, i.e. the DEC VAX days of yore.
```

Original comment by `steven.k...@gmail.com` on 4 Jun 2008 at 3:33

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 25 May 2009 at 1:02
- Changed state: **Done**
